release:
  github:
    owner: chanyipiaomiao
    name: novels
  name_template: '{{.Tag}}'
  draft: true
builds:
- main: main.go
  binary: novels
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  - 386
  - arm64
  env:
  - CGO_ENABLED=0
archive:
  format: tar.gz
  wrap_in_directory: true
  replacements:
    amd64: 64-bit
    darwin: macos
    linux: linux
  files:
  - LICENSE
  - README.md
  - conf/*.conf
  format_overrides:
  - goos: windows
    format: zip